version: "3.8"

services:
  accumula_backend:
    build:
      context: ./accumula_backend
    ports:
      - "5000:5000"

  accumula_frontend:
    build:
      context: ./accumula_frontend
    ports:
      - "4200:4200"
    depends_on:
      - accumula_backend
    
